name: Update badges

on:
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    environment:
       name: stage
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: davi-araujo-caetano-de-carvalho
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
